spring.application.name=payment-processing-system

# SQL Server Database Configuration
spring.datasource.url=JDBC:sqlserver://localhost:1433;databaseName=paymentdb;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=root

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080